// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
aws_app_analytics : 'enable',
aws_cognito_identity_pool_id : 'us-east-1:6ee23c0c-b3e8-415a-9d20-c6173f5187e3',
aws_cognito_region : 'us-east-1',
aws_content_delivery : 'enable',
aws_content_delivery_bucket : 'elderlift-hosting-mobilehub-942361379',
aws_content_delivery_bucket_region : 'us-east-1',
aws_content_delivery_cloudfront : 'enable',
aws_content_delivery_cloudfront_domain : 'ddpzo5y14wiav.cloudfront.net',
aws_mobile_analytics_app_id : '218741d459834cf7b426e2ae08d907b7',
aws_project_id : '5b45158e-a570-4e5e-919f-12d0203894f0',
aws_project_name : 'elderLift',
aws_project_region : 'us-east-1',
aws_resource_name_prefix : 'elderlift-mobilehub-942361379',
aws_sign_in_enabled : 'enable',
aws_user_pools : 'enable',
aws_user_pools_id : 'us-east-1_WnOXa7KQ3',
aws_user_pools_mfa_type : 'OPTIONAL',
aws_user_pools_web_client_id : '1nr72047b4fc8ake387994lg1r',
}

export default awsmobile;
var AWS = require('aws-sdk');
AWS.config.region = awsmobile.aws_project_region;
AWS.config.update({customUserAgent: 'MobileHub v0.1'});