// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
aws_app_analytics : 'enable',
aws_cognito_identity_pool_id : 'us-east-1:3e6f8f34-4745-4c50-b0bf-c876af8872f1',
aws_cognito_region : 'us-east-1',
aws_content_delivery : 'enable',
aws_content_delivery_bucket : 'elderlift-hosting-mobilehub-1333657238',
aws_content_delivery_bucket_region : 'us-east-1',
aws_content_delivery_cloudfront : 'enable',
aws_content_delivery_cloudfront_domain : 'd1nowmjvtyt76q.cloudfront.net',
aws_mobile_analytics_app_id : '37a5d8a51cb74bffa4a9a08cc665d8cb',
aws_project_id : 'c3333580-e83a-43cb-a712-95bd60aeca99',
aws_project_name : 'elderLift',
aws_project_region : 'us-east-1',
aws_resource_name_prefix : 'elderlift-mobilehub-1333657238',
}

export default awsmobile;
var AWS = require('aws-sdk');
AWS.config.region = awsmobile.aws_project_region;
AWS.config.update({customUserAgent: 'MobileHub v0.1'});